Asp.Net/FoodDelievery/FastFood.Web/Areas/Admin/Controllers/ItemController.cs
using FastFood.Models;
using FastFood.Repositories;
using FastFood.Web.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

//namespace FastFood.Web.Areas.Admin.Controllers
//{
//    [Area("Admin")]
//    public class ItemController : Controller
//    {
//        private readonly ApplicationDbContext _context;
//        private readonly IWebHostEnvironment _webHostEnvironment;

//        public ItemController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
//        {
//            _context = context;
//            _webHostEnvironment = webHostEnvironment;
//        }

//        // GET: Admin/Item
//        [HttpGet]
//        public IActionResult Index()
//        {
//            var items = _context.Items.Include(x => x.Category).Include(y => y.SubCategory).ToList();
//            return View(items);
//        }

//        // GET: Admin/Item/Create
//        [HttpGet]
//        public IActionResult Create()
//        {
//            ItemViewModel vm = new ItemViewModel();
//            ViewBag.Category = new SelectList(_context.Categories, "Id", "Title");
//            return View(vm);
//        }

//        // POST: Admin/Item/Create
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public async Task<IActionResult> Create(ItemViewModel vm)
//        {
//            if (ModelState.IsValid)
//            {
//                Item model = new Item
//                {
//                    Name = vm.Name,
//                    Description = vm.Description,
//                    Price = vm.Price,
//                    CategoryId = vm.CategoryId,
//                    SubCategoryId = vm.SubCategoryId
//                };

//                if (vm.ImageUrl != null && vm.ImageUrl.Length > 0)
//                {
//                    var uploadDir = @"Images/Items";
//                    var filename = Guid.NewGuid().ToString() + "-" + Path.GetFileName(vm.ImageUrl.FileName);
//                    var path = Path.Combine(_webHostEnvironment.WebRootPath, uploadDir, filename);

//                    if (!Directory.Exists(Path.Combine(_webHostEnvironment.WebRootPath, uploadDir)))
//                    {
//                        Directory.CreateDirectory(Path.Combine(_webHostEnvironment.WebRootPath, uploadDir));
//                    }

//                    using (var fileStream = new FileStream(path, FileMode.Create))
//                    {
//                        await vm.ImageUrl.CopyToAsync(fileStream);
//                    }

//                    model.ImageUrl = "/" + uploadDir + "/" + filename;
//                }

//                _context.Items.Add(model);
//                await _context.SaveChangesAsync();
//                return RedirectToAction(nameof(Index));
//            }

//            ViewBag.Category = new SelectList(_context.Categories, "Id", "Title");
//            return View(vm);
//        }

//        // GET: Admin/Item/Edit/5
//        [HttpGet]
//        public IActionResult Edit(int? id)
//        {
//            if (id == null)
//            {
//                return NotFound();
//            }

//            var item = _context.Items.Find(id);
//            if (item == null)
//            {
//                return NotFound();
//            }

//            var vm = new ItemViewModel
//            {
//                Id = item.Id,
//                Name = item.Name,
//                Description = item.Description,
//                Price = item.Price,
//                CategoryId = item.CategoryId,
//                SubCategoryId = item.SubCategoryId,
//               // ImageUrl = item.Image
//            };

//            ViewBag.Category = new SelectList(_context.Categories, "Id", "Title", vm.CategoryId);
//            return View(vm);
//        }

//        // POST: Admin/Item/Edit/5
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public async Task<IActionResult> Edit(int id, ItemViewModel vm)
//        {
//            if (id != vm.Id)
//            {
//                return NotFound();
//            }

//            if (ModelState.IsValid)
//            {
//                try
//                {
//                    var item = await _context.Items.FindAsync(id);
//                    if (item == null)
//                    {
//                        return NotFound();
//                    }

//                    item.Name = vm.Name;
//                    item.Description = vm.Description;
//                    item.Price = vm.Price;
//                    item.CategoryId = vm.CategoryId;
//                    item.SubCategoryId = vm.SubCategoryId;

//                    if (vm.ImageUrl != null && vm.ImageUrl.Length > 0)
//                    {
//                        var uploadDir = @"Images/Items";
//                        var filename = Guid.NewGuid().ToString() + "-" + Path.GetFileName(vm.ImageUrl.FileName);
//                        var path = Path.Combine(_webHostEnvironment.WebRootPath, uploadDir, filename);

//                        if (!Directory.Exists(Path.Combine(_webHostEnvironment.WebRootPath, uploadDir)))
//                        {
//                            Directory.CreateDirectory(Path.Combine(_webHostEnvironment.WebRootPath, uploadDir));
//                        }

//                        using (var fileStream = new FileStream(path, FileMode.Create))
//                        {
//                            await vm.ImageUrl.CopyToAsync(fileStream);
//                        }

//                        // Delete old image if new image is uploaded
//                        if (!string.IsNullOrEmpty(item.ImageUrl))
//                        {
//                            var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, item.ImageUrl.TrimStart('/'));
//                            if (System.IO.File.Exists(oldImagePath))
//                            {
//                                System.IO.File.Delete(oldImagePath);
//                            }
//                        }

//                        item.ImageUrl = "/" + uploadDir + "/" + filename;
//                    }

//                    _context.Update(item);
//                    await _context.SaveChangesAsync();
//                }
//                catch (DbUpdateConcurrencyException)
//                {
//                    if (!ItemExists(vm.Id))
//                    {
//                        return NotFound();
//                    }
//                    else
//                    {
//                        throw;
//                    }
//                }

//                return RedirectToAction(nameof(Index));
//            }

//            ViewBag.Category = new SelectList(_context.Categories, "Id", "Title", vm.CategoryId);
//            return View(vm);
//        }

//        // GET: Admin/Item/Delete/5
//        [HttpGet]
//        public IActionResult Delete(int? id)
//        {
//            if (id == null)
//            {
//                return NotFound();
//            }

//            var item = _context.Items.Include(i => i.Category).Include(i => i.SubCategory)
//                .FirstOrDefault(m => m.Id == id);

//            if (item == null)
//            {
//                return NotFound();
//            }

//            return View(item);
//        }

//        // POST: Admin/Item/Delete/5
//        [HttpPost, ActionName("Delete")]
//        [ValidateAntiForgeryToken]
//        public async Task<IActionResult> DeleteConfirmed(int id)
//        {
//            var item = await _context.Items.FindAsync(id);
//            if (item == null)
//            {
//                return NotFound();
//            }

//            // Delete the image file
//            if (!string.IsNullOrEmpty(item.ImageUrl))
//            {
//                var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, item.ImageUrl.TrimStart('/'));
//                if (System.IO.File.Exists(imagePath))
//                {
//                    System.IO.File.Delete(imagePath);
//                }
//            }

//            _context.Items.Remove(item);
//            await _context.SaveChangesAsync();
//            return RedirectToAction(nameof(Index));
//        }

//        private bool ItemExists(int id)
//        {
//            return _context.Items.Any(e => e.Id == id);
//        }
//    }
//}



namespace FastFood.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IWebHostEnvironment _webHostEnvironment;
        public ItemController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var items = _context.Items.Include(x => x.Category).Include(y => y.SubCategory).ToList();
            return View(items); 
        }


        [HttpGet]
        public IActionResult Create()
        {
            ItemViewModel vm = new ItemViewModel();
            ViewBag.Category = new SelectList(_context.Categories, "Id", "Title");
            return View(vm);
        }

        [HttpGet]
        public IActionResult GetSubCategory(int categoryId)
        {
            var subCategory = _context.SubCategories.Where(x => x.CategoryId == categoryId).FirstOrDefault();
            return Json(subCategory);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ItemViewModel vm)
        {
            Item model = new Item();
            if (ModelState.IsValid)
            {
                if (vm.ImageUrl != null && vm.ImageUrl.Length > 0)
                {
                    var uploadDir = @"Images/Items";

Asp.Net/FoodDelievery/FastFood.Web/Areas/Admin/Controllers/SubCategoriesController.cs
using FastFood.Models;
using FastFood.Repositories;
using FastFood.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FastFood.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SubCategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SubCategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var subCategory=_context.SubCategories.Include(x => x.Category).ToList();
            return View(subCategory);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            SubCategoryViewModel vm = new SubCategoryViewModel();
            ViewBag.category = new SelectList(_context.Categories, "Id", "Title");
            return View(vm);
        }

        [HttpPost]
        public IActionResult Create(SubCategoryViewModel vm)
        {
            if (ModelState.IsValid)
            {
                SubCategory model = new SubCategory();
                model.Title = vm.Title;
                model.CategoryId = vm.CategoryId;
                _context.SubCategories.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vm);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            SubCategoryViewModel vm = new SubCategoryViewModel();
            var subCategory = _context.SubCategories.Where(x=>x.Id == id).FirstOrDefault();
            if (subCategory!= null)
            {
                vm.Id = subCategory.Id;
                vm.Title = subCategory.Title;
                ViewBag.category = new SelectList(_context.Categories, "Id", "Title",subCategory.CategoryId);
            }
            return View(vm);
        }

        [HttpPost]
        public IActionResult Edit(SubCategoryViewModel vm)
        {
            if (ModelState.IsValid)
            {
                SubCategory model = new SubCategory();
                model.Title = vm.Title;
                model.CategoryId = vm.CategoryId;
                _context.SubCategories.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vm);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            SubCategoryViewModel vm = new SubCategoryViewModel();
            var subCategory = _context.SubCategories.Where(x => x.Id == id).FirstOrDefault();
            if (subCategory != null)
            {
                _context.SubCategories.Remove(subCategory);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Asp.Net/FoodDelievery/FastFood.Web/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FastFood.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FastFood.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FastFood.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="categories" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="SubCategories" asp-action="Index">Sub Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FastFood.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
*@


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FastFood.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FastFood.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FastFood.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="categories" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="SubCategories" asp-action="Index">Sub Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Item" asp-action="Index">Item</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="coupons" asp-action="Index">Coupon</a>
                        </li>
                    </ul>
                    @*<ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="form-inline">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>*@
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="form-inline">
                                    @Html.AntiForgeryToken()
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>


                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FastFood.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>